name: learn_flutter_67_1_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  connectivity_plus: ^6.1.5
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ตั้งค่า launcher icon
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "./android/assets/icon/icon.png" # ✅ ไม่ต้องมี .android
  min_sdk_android: 28
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - ./android/assets/image/app.png   # ✅ เอา "/" ด้านหน้าสุดออก
